sudo: required

language: scala

scala:
  - 2.11.5

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - docker-compose up -d
  - docker ps -a
  - curl http://127.0.0.1:8500/v1/catalog/service/elasticsearch-9200

script:
  - echo "success"
