sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - docker-compose up -d
  - docker ps -a

script:
  - sbt ++$TRAVIS_SCALA_VERSION test updateImpactSubmit
