consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: gliderlabs/consul-server:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    #- "172.17.0.1:53:8600/udp"

registrator:
  command: -ip 172.17.0.1 consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
    - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

elastic:
  image: "elasticsearch:latest"
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  ports:
    - "9200:9200"
  environment:
    SERVICE_NAME: elastic
    SERVICE_TAGS: search
    SERVICE_CHECK_HTTP: /
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s

mattermost:
  image: mattermost/platform:2.0
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  ports:
    - "8080:80"
  environment:
    SERVICE_NAME: mm
    SERVICE_TAGS: chat
    SERVICE_CHECK_HTTP: /
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s
